In [ ]:
!pip install pandas

In [1]:
import numpy as np
import pandas as pd

In [ ]:

my_list = [10, 20, 40]
labels = ['a', 'b', 'c']
d={'a':10,'b':20,'c':30}

In [ ]:
pd.Series(my_list)

In [ ]:
pd.Series(my_list, index=labels)

In [ ]:
pd.Series(d)

DataFrame in dictionary

In [ ]:

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan'],
    'Age': [25, 30, 35, 28, 40],
    'City': ['New York', 'London', 'Paris', 'Berlin', 'Tokyo'],
    'Occupation': ['Engineer', 'Designer', 'Teacher', 'Doctor', 'Chef']
}

In [ ]:
df=pd.DataFrame(data)
df

DataFrame in List

In [ ]:
data_List = [
     ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan'],
      [25, 30, 35, 28, 40],
     ['New York', 'London', 'Paris', 'Berlin', 'Tokyo'],
     ['Engineer', 'Designer', 'Teacher', 'Doctor', 'Chef']
]
column=['name','age','city','accupation']

In [ ]:
df2=pd.DataFrame(data_List,index=column).T
df2

Selecting column

In [ ]:
df2['name']

Adding a new Column

In [ ]:
df2["age_factor"]=["genz","milenial","milenial","genz","milenial"]

In [ ]:
df2

Remove column

In [ ]:
df2.drop("age",axis=1)

Age drop ho gyi but agar ham dubara dekhe toh hogi

In [ ]:
df2

Toh sahi se delete karne ke liye ham inplace use krte hn

In [ ]:
df2.drop("age",axis=1,inplace=True)
df2

u can delete 2 or more also and aslo row by making axis=0

In [ ]:
df2.drop(["name","city"],axis=1)

Selecting column(it is different than selecting column)

In [ ]:
df2.loc[0]

In [ ]:
df2.loc[[0,1]]

Selecting Subsets of rows and column

In [ ]:
df2.loc[[3,4]][["name","city"]]

Conditional Selection

# i only wanna select people of age_factor genz

In [ ]:
df2[df2["age_factor"]=="genz"]

In [ ]:
df2[(df2["age_factor"] == "genz") & (df2["city"] == "Berlin")]

Missing data

In [ ]:


data = {
    "Name": ["Ali", "Sara", "Ayesha", "Zoya"],
    "Age": [19, np.nan, 18, 21],
    "City": ["Karachi", np.nan, "Islamabad", np.nan],
    "Marks": [85, 92, np.nan, 88]
}

df3 = pd.DataFrame(data)
df3

In [ ]:
df3.isna().sum()

any for seeing ke har ek column mai null value hai

In [ ]:
df3.any()

Removing Missing value (ye rows ke basis pe work karta)

In [ ]:
df3

In [ ]:
df3.dropna()

Thresh use hota hai as a condition ke jaha 3 ya 2 non null value usko remove na karo baki ko kardo

In [ ]:
df3.dropna(thresh=3)

Filling the missing data

In [ ]:
df3

In [ ]:
df3.fillna("missing")

In [ ]:
values={"Age":17,"City":"lahore"}
df3.fillna(value=values)

Merge Joining and concatination

In [43]:
students = {
    "Student_ID": [101, 102, 103, 104],
    "Name": ["Ali", "Sara", "Ahmed", "Zoya"],
    "City": ["Karachi", "Lahore", "Islamabad", "Karachi"]
}
marks = {
    "Student_ID": [101, 102, 104, 105],
    "Marks": [85, 92, 88, 75],
    "Grade": ["A", "A+", "B+", "B"]
} 
df_students=pd.DataFrame(students)
df_students

   Student_ID   Name       City
0         101    Ali    Karachi
1         102   Sara     Lahore
2         103  Ahmed  Islamabad
3         104   Zoya    Karachi

In [44]:

df_marks=pd.DataFrame(marks)
df_marks

   Student_ID  Marks Grade
0         101     85     A
1         102     92    A+
2         104     88    B+
3         105     75     B

In [49]:
pd.merge(df_students, df_marks, on='Student_ID')

   Student_ID  Name     City  Marks Grade
0         101   Ali  Karachi     85     A
1         102  Sara   Lahore     92    A+
2         104  Zoya  Karachi     88    B+

In [50]:
pd.merge(df_students, df_marks, on='Student_ID',how='outer')

   Student_ID   Name       City  Marks Grade
0         101    Ali    Karachi   85.0     A
1         102   Sara     Lahore   92.0    A+
2         103  Ahmed  Islamabad    NaN   NaN
3         104   Zoya    Karachi   88.0    B+
4         105    NaN        NaN   75.0     B

In [51]:
pd.merge(df_students, df_marks, on='Student_ID',how='right')

   Student_ID  Name     City  Marks Grade
0         101   Ali  Karachi     85     A
1         102  Sara   Lahore     92    A+
2         104  Zoya  Karachi     88    B+
3         105   NaN      NaN     75     B

Concatination

In [53]:


df1 = pd.DataFrame({
    "Name": ["Ali", "Sara"],
    "Marks": [85, 90]
})

df2 = pd.DataFrame({
    "Name": ["Ahmed", "Zoya"],
    "Marks": [75, 88]
})

pd.concat([df1, df2])

    Name  Marks
0    Ali     85
1   Sara     90
0  Ahmed     75
1   Zoya     88

In [54]:
pd.concat([df1, df2], axis=1)

   Name  Marks   Name  Marks
0   Ali     85  Ahmed     75
1  Sara     90   Zoya     88

joining

In [57]:
df1 = pd.DataFrame({
    "Name": ["Ali", "Sara", "Ahmed"],
    "Marks": [85, 90, 78]
}, index=[1, 2, 3])

df2 = pd.DataFrame({
    "City": ["Karachi", "Lahore", "Islamabad"]
}, index=[1, 2, 3)

In [56]:
 df1.join(df2)

    Name  Marks       City
1    Ali     85    Karachi
2   Sara     90     Lahore
3  Ahmed     78  Islamabad

Group By

In [6]:
data = {
    "Department": ["IT", "HR", "IT", "HR"],
    "Salary": [50000, 40000, 60000, 45000]
}
df=pd.DataFrame(data)
df

  Department  Salary
0         IT   50000
1         HR   40000
2         IT   60000
3         HR   45000

In [12]:
df.groupby('Salary')['Department'].sum()

Salary
40000    HR
45000    HR
50000    IT
60000    IT
Name: Department, dtype: object

Aggregation

In [14]:
df['Salary'].mean()

np.float64(48750.0)

In [16]:
df.groupby("Department")["Salary"].agg(
    ["mean","median", "max", "min"]
)

               mean   median    max    min
Department
HR          42500.0  42500.0  45000  40000
IT          55000.0  55000.0  60000  50000

Pivot Table

In [15]:

data = {
    "Name": ["Ali", "Sara", "Ahmed", "Zoya"],
    "Department": ["IT", "HR", "IT", "HR"],
    "Salary": [50000, 60000, 55000, 65000]
}

df = pd.DataFrame(data)
df

    Name Department  Salary
0    Ali         IT   50000
1   Sara         HR   60000
2  Ahmed         IT   55000
3   Zoya         HR   65000

In [5]:
pd.pivot_table(  df,  values="Salary",  index="Department", aggfunc="mean"
)

             Salary
Department
HR          62500.0
IT          52500.0

In [6]:
pd.crosstab(df["Department"], df["Name"])

Name        Ali  Sara  Zoya
Department
HR            0     1     1
IT            2     0     0

Operations

In [7]:
df.shape

(4, 3)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        4 non-null      object
 1   Department  4 non-null      object
 2   Salary      4 non-null      int64
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        4 non-null      object
 1   Department  4 non-null      object
 2   Salary      4 non-null      int64
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [16]:
df.head(2)

   Name Department  Salary
0   Ali         IT   50000
1  Sara         HR   60000

In [17]:
df.tail(2)

    Name Department  Salary
2  Ahmed         IT   55000
3   Zoya         HR   65000

In [18]:
df.columns

Index(['Name', 'Department', 'Salary'], dtype='object')

In [19]:
df.dtypes

Name          object
Department    object
Salary         int64
dtype: object

In [20]:
df.describe()

             Salary
count      4.000000
mean   57500.000000
std     6454.972244
min    50000.000000
25%    53750.000000
50%    57500.000000
75%    61250.000000
max    65000.000000

In [21]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [22]:
df.size

12

In [23]:
df.ndim

2